### ISSUE TITLE
Using Kafka for fall detection

### ISSUE THREAD

**Issue by gigwegbe** [JustinhoCHN/fall-detection#1]
Hello @JustinhoCHN,
Thanks for the awesome on fall detection, however, I have been unable to run the docker image(server error). I have a couple of questions:

1. How to use Kafka protocol instead was protocol. 
2. How can I run the fall detection locally instead of using the docker container. 
2. What do model did you use for the fall detection and how can I retrain it for another task(e.g book detection).

Thanks.

**Comment by JustinhoCHN** [comment]
If the deepstream-test5 app contains all of your needs, I would suggest you to use deepstream-test5-app instead of test4. 

Test5 app should be modified with some lines if you want to customize the kafka message format.

1. ```deepstream_test5_app_main.c```
- meta_copy_func
- meta_free_func
- generate_event_msg_meta
- generate_person_meta 

2. ```/opt/nvidia/deepstream/deepstream-5.0/sources/includes/nvdsmeta_schema.h```
this's for adding a custom object type which contains the attribute you want.
- modify the ```NvDsPersonObject```, add the attributes you want.
- or you can just add a new object, and use it in ```deepstream_test5_app_main.c```

3. ```/opt/nvidia/deepstream/deepstream-5.0/sources/libs/nvmsgconv/nvmsgconv.cpp```
this's for how to send your custom message properly.
- ```generate_deepstream_message_minimal```
you can take this for example:
```
case NVDS_OBJECT_TYPE_PERSON: {
          NvDsPersonObject *dsObj = (NvDsPersonObject *) meta->extMsg;
          if (dsObj) {
            ss << "|#|" << to_str(dsObj->gender) << "|" << dsObj->age << "|"
                << to_str(dsObj->hair) << "|" << to_str(dsObj->cap) << "|" << to_str(dsObj->apparel)
                << "|" << meta->confidence;
          }
        }
          break;
```

You have to read these code mentioned above for a couple days, then you'll know all you have to do is just copy and plaste and change some little parts.  Be patient.
